#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

RWTexture3D<float4> OutputTexture;

float4 ClearColor;
int3 TextureSize;

[numthreads(4, 4, 4)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	if (DispatchThreadId.x >= TextureSize.x ||
		DispatchThreadId.y >= TextureSize.y ||
		DispatchThreadId.z >= TextureSize.z)
	{
		return;
	}

	OutputTexture[DispatchThreadId.xyz] = ClearColor;
}