#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

RWTexture2D<float4> OutputTexture;
float DeltaTime;
float RecoveryRate;
int2 TextureSize;

[numthreads(8, 8, 1)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	if (DispatchThreadId.x >= TextureSize.x || DispatchThreadId.y >= TextureSize.y)
	{
		return;
	}

	float4 oldValue = OutputTexture[DispatchThreadId.xy];

	float newValue = max(oldValue.r - DeltaTime * RecoveryRate, 0.0);

	OutputTexture[DispatchThreadId.xy] = float4(newValue, newValue, newValue, 1.0);
}