#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

RWTexture2D<float4> OutputTexture;
float4 FillColor;

[numthreads(8, 8, 1)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint Width, Height;
	OutputTexture.GetDimensions(Width, Height);

	if (DispatchThreadId.x >= Width || DispatchThreadId.y >= Height)
	{
		return;
	}

	OutputTexture[DispatchThreadId.xy] = FillColor;
}